@ECHO OFF
CLS
ECHO Welcome to CavaPlugin Fix
ECHO This batch will update all CavaPlugin Folders and clean HB Cache
PAUSE
CLS
ECHO Removing Honorbuddy Cache Folder.
rmdir /s/q "..\..\Cache"
ECHO ...
ECHO ...
ECHO ...
ECHO Updating Cava Plugin Folder.
ECHO Wait UNTILL finish then press any key.....
START TortoiseProc.exe /command:"update" /path:"..\CavaPlugin" /closeonend:1
PAUSE
ECHO ...
ECHO ...
ECHO ...
ECHO Updating Cava QuestBehaviors Folder.
ECHO Wait UNTILL finish then press any key.....
START TortoiseProc.exe /command:"update" /path:"..\..\Quest Behaviors\Cava" /closeonend:1
PAUSE
ECHO ...
ECHO ...
ECHO ...
ECHO Updating Cava Profiles Folder.
ECHO Wait UNTILL finish then press any key.....
START TortoiseProc.exe /command:"update" /path:"..\..\Default Profiles\Cava" /closeonend:1
PAUSE
EXIT